/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.awt.event.*;
import java.sql.*;
import java.text.*;
import javax.swing.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
import javax.swing.table.DefaultTableModel;
import static main.GPA_Yes.UnweightedGPA_ComboBox;
import static main.GPA_Yes.WeightedGPA_ComboBox;
import static main.SAT_Yes.SATSuperscore_TextField;
import static main.TOEFL_Yes.TOEFLScore_TextField;
import static main.IB_Yes.TotalIBScore_TextField;
import static main.Field.FirstChoice_ComboBox;
import static main.Field.SecondChoice_ComboBox;
import static main.Academics.StudentID;
import static main.GPA_Yes.UnweightedGPA_ComboBox;
import static main.GPA_Yes.WeightedGPA_ComboBox;


/**
 *
 * @author Sandeep
 */
public class Academics extends javax.swing.JFrame {
DefaultTableModel model;
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;

    public Academics() {
        initComponents();
        Show_Users_In_JTable();
    }
    
public Connection getConnection()
   {
       Connection con;
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/StudentBase", "root","");
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
        

 // get a list of users from mysql database
   public ArrayList<Useer> getUsersList()
   {
       ArrayList<Useer> usersList = new ArrayList<Useer>();
       Connection connection = getConnection();
       
       String query = "SELECT * FROM  `studentbase`";
       Statement st;
       ResultSet rs;
       
       try {
           st = connection.createStatement();
           rs = st.executeQuery(query);
           Useer user;
           while(rs.next())
           {
               user = new Useer(rs.getString("UnweightedGPA"),rs.getString("WeightedGPA"),rs.getString("SATScore"),rs.getString("StudentID"), rs.getString("TOEFLScore"), 
                                rs.getString("IBScore"));
               usersList.add(user);
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
       return usersList;
   }
   
   // Display Data In JTable
   
   public void Show_Users_In_JTable()
   {
       ArrayList<Useer> list = getUsersList();
       
       Object[] row = new Object[6];
       for(int i = 0; i < list.size(); i++)
       {
           row[0] = list.get(i).getStudentID();
           row[1] = list.get(i).getUnweightedGPA();
           row[2] = list.get(i).getWeightedGPA();
           row[3] = list.get(i).getSATScore();
           row[4] = list.get(i).getTOEFLScore();
           row[5] = list.get(i).getIBScore();
           
           DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
           model.addRow(row);
       }
    }
        
   // Execute The Insert Update And Delete Querys
   public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
               model.setRowCount(0);
               Show_Users_In_JTable();
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        AcademicsPage_Label = new javax.swing.JLabel();
        GoBack_Label = new javax.swing.JLabel();
        SATScore_Label = new javax.swing.JLabel();
        TOEFLScore_Label = new javax.swing.JLabel();
        APGrades_Label = new javax.swing.JLabel();
        IB_Yes_Button = new javax.swing.JToggleButton();
        AP_Yes_Button = new javax.swing.JToggleButton();
        SAT_Yes_Button = new javax.swing.JToggleButton();
        TOEFL_Yes_Button = new javax.swing.JToggleButton();
        APGrades_Label1 = new javax.swing.JLabel();
        APGrades_Label2 = new javax.swing.JLabel();
        GPA_Yes_Button = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        SearchAll_Button = new javax.swing.JToggleButton();
        Next_Button = new javax.swing.JToggleButton();
        APGrades_Label3 = new javax.swing.JLabel();
        StudentID = new javax.swing.JTextField();
        Update_Button = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });

        AcademicsPage_Label.setFont(new java.awt.Font("Raleway ExtraBold", 1, 24)); // NOI18N
        AcademicsPage_Label.setForeground(new java.awt.Color(255, 255, 255));
        AcademicsPage_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AcademicsPage_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Home_48px_1.png"))); // NOI18N
        AcademicsPage_Label.setText("Academics");

        GoBack_Label.setBackground(new java.awt.Color(255, 255, 255));
        GoBack_Label.setForeground(new java.awt.Color(255, 255, 255));
        GoBack_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Long_Arrow_Left_48px_2.png"))); // NOI18N
        GoBack_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GoBack_LabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GoBack_Label)
                    .addComponent(AcademicsPage_Label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AcademicsPage_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoBack_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        SATScore_Label.setFont(new java.awt.Font("Raleway ExtraBold", 0, 18)); // NOI18N
        SATScore_Label.setForeground(new java.awt.Color(45, 118, 232));
        SATScore_Label.setText("SAT Score:");

        TOEFLScore_Label.setFont(new java.awt.Font("Raleway ExtraBold", 0, 18)); // NOI18N
        TOEFLScore_Label.setForeground(new java.awt.Color(45, 118, 232));
        TOEFLScore_Label.setText("TOEFL Score:");

        APGrades_Label.setFont(new java.awt.Font("Raleway ExtraBold", 0, 18)); // NOI18N
        APGrades_Label.setForeground(new java.awt.Color(45, 118, 232));
        APGrades_Label.setText("AP Grades:");

        IB_Yes_Button.setFont(new java.awt.Font("Raleway SemiBold", 2, 11)); // NOI18N
        IB_Yes_Button.setText("YES");
        IB_Yes_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IB_Yes_ButtonActionPerformed(evt);
            }
        });

        AP_Yes_Button.setFont(new java.awt.Font("Raleway SemiBold", 2, 11)); // NOI18N
        AP_Yes_Button.setText("YES");
        AP_Yes_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AP_Yes_ButtonActionPerformed(evt);
            }
        });

        SAT_Yes_Button.setFont(new java.awt.Font("Raleway SemiBold", 2, 11)); // NOI18N
        SAT_Yes_Button.setText("YES");
        SAT_Yes_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAT_Yes_ButtonActionPerformed(evt);
            }
        });

        TOEFL_Yes_Button.setFont(new java.awt.Font("Raleway SemiBold", 2, 11)); // NOI18N
        TOEFL_Yes_Button.setText("YES");
        TOEFL_Yes_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOEFL_Yes_ButtonActionPerformed(evt);
            }
        });

        APGrades_Label1.setFont(new java.awt.Font("Raleway ExtraBold", 0, 18)); // NOI18N
        APGrades_Label1.setForeground(new java.awt.Color(45, 118, 232));
        APGrades_Label1.setText("IB Predicted Grades:");

        APGrades_Label2.setFont(new java.awt.Font("Raleway ExtraBold", 0, 18)); // NOI18N
        APGrades_Label2.setForeground(new java.awt.Color(45, 118, 232));
        APGrades_Label2.setText("GPA:");

        GPA_Yes_Button.setFont(new java.awt.Font("Raleway SemiBold", 2, 11)); // NOI18N
        GPA_Yes_Button.setText("YES");
        GPA_Yes_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GPA_Yes_ButtonMouseClicked(evt);
            }
        });
        GPA_Yes_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPA_Yes_ButtonActionPerformed(evt);
            }
        });

        StudentTable.setFont(new java.awt.Font("Raleway Medium", 0, 12)); // NOI18N
        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"86876", null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {"9878786", null, null, null, null, null}
            },
            new String [] {
                "StudentID", "UnweightedGPA", "WeightedGPA", "SATScore", "TOEFLScore", "IBScore"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(StudentTable);

        SearchAll_Button.setFont(new java.awt.Font("Raleway SemiBold", 2, 11)); // NOI18N
        SearchAll_Button.setText("SEARCH ALL");
        SearchAll_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchAll_ButtonMouseClicked(evt);
            }
        });
        SearchAll_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchAll_ButtonActionPerformed(evt);
            }
        });

        Next_Button.setFont(new java.awt.Font("Raleway SemiBold", 2, 11)); // NOI18N
        Next_Button.setText("NEXT");
        Next_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Next_ButtonMouseClicked(evt);
            }
        });
        Next_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_ButtonActionPerformed(evt);
            }
        });

        APGrades_Label3.setFont(new java.awt.Font("Raleway ExtraBold", 0, 18)); // NOI18N
        APGrades_Label3.setForeground(new java.awt.Color(45, 118, 232));
        APGrades_Label3.setText("Student ID: ");

        Update_Button.setFont(new java.awt.Font("Raleway SemiBold", 2, 11)); // NOI18N
        Update_Button.setText("UPDATE");
        Update_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_ButtonMouseClicked(evt);
            }
        });
        Update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Next_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257)
                        .addComponent(SearchAll_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Update_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TOEFLScore_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TOEFL_Yes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(APGrades_Label2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GPA_Yes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SATScore_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SAT_Yes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(APGrades_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AP_Yes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(APGrades_Label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IB_Yes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(APGrades_Label3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(APGrades_Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GPA_Yes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(APGrades_Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IB_Yes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(APGrades_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(APGrades_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AP_Yes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SATScore_Label)
                            .addComponent(SAT_Yes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TOEFL_Yes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TOEFLScore_Label))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchAll_Button)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Next_Button)
                        .addComponent(Update_Button)))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        System.exit(0);    // TODO add your handling code here:
    }//GEN-LAST:event_ExitMousePressed

    private void GoBack_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBack_LabelMousePressed
this.hide();
Home frm=new Home();
frm.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBack_LabelMousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
int x = evt.getXOnScreen();
int y = evt.getYOnScreen();
this.setLocation(x - xx, y - xy);           // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged
int xx, xy;

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
     xx = evt.getX();
     xy = evt.getY();   // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    private void IB_Yes_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IB_Yes_ButtonActionPerformed
this.show();
IB_Yes frm=new IB_Yes();
frm.setVisible(true);
    }//GEN-LAST:event_IB_Yes_ButtonActionPerformed

    private void SAT_Yes_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAT_Yes_ButtonActionPerformed
this.show();
SAT_Yes frm = new SAT_Yes();
frm.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SAT_Yes_ButtonActionPerformed

    private void TOEFL_Yes_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOEFL_Yes_ButtonActionPerformed
   this.show();
TOEFL_Yes frm=new TOEFL_Yes();
frm.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_TOEFL_Yes_ButtonActionPerformed

    private void GPA_Yes_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPA_Yes_ButtonActionPerformed
this.show();
GPA_Yes frm=new GPA_Yes();
frm.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_GPA_Yes_ButtonActionPerformed

    private void SearchAll_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchAll_ButtonActionPerformed
 
    }//GEN-LAST:event_SearchAll_ButtonActionPerformed

    private void SearchAll_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchAll_ButtonMouseClicked
 try {
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/StudentBase","root","");
        // TODO add your handling code here:
        pst = conn.prepareStatement("INSERT INTO `studentbase`(`StudentID`, `UnweightedGPA`, `WeightedGPA`, SATScore, TOEFLScore, IBScore) "
                + "VALUES (?,?,?,?,?,?)");
                
       
        pst.setString(1, (String) StudentID.getText());
        pst.setString(2, (String) UnweightedGPA_ComboBox.getSelectedItem());
        pst.setString(3, (String) WeightedGPA_ComboBox.getSelectedItem());
        pst.setString(4, (String) SATSuperscore_TextField.getText());
        pst.setString(5, (String) TOEFLScore_TextField.getText());
        pst.setString(6, (String) TotalIBScore_TextField.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Inserted");
        
        
    } catch (SQLException ex) {
        Logger.getLogger(GPA_Yes.class.getName()).log(Level.SEVERE, null, ex);
       
    }          
        DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
        model.setRowCount(0);
        Show_Users_In_JTable(); 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchAll_ButtonMouseClicked

    private void Next_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Next_ButtonMouseClicked

    private void Next_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_ButtonActionPerformed

    this.hide();
Home frm=new Home();
frm.setVisible(true);

          // TODO add your handling code here:
    }//GEN-LAST:event_Next_ButtonActionPerformed

    private void GPA_Yes_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GPA_Yes_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GPA_Yes_ButtonMouseClicked

    private void Update_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_ButtonMouseClicked

    private void Update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ButtonActionPerformed
try {
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/StudentBase","root","");
         String UnweightedGPA=(String) UnweightedGPA_ComboBox.getSelectedItem();
        String WeightedGPA = (String) WeightedGPA_ComboBox.getSelectedItem();
        String IBScore = (String) TotalIBScore_TextField.getText();
        String TOEFLScore = (String) TOEFLScore_TextField.getText();
        String SATScore = (String) SATSuperscore_TextField.getText();
        
        String query = "update studentbase set UnweightedGPA = ?, WeightedGPA = ?, TOEFLScore = ?, SATScore = ?, IBScore = ? where StudentID = ?";
      PreparedStatement preparedStmt = conn.prepareStatement(query);
      preparedStmt.setString(2, WeightedGPA);
      preparedStmt.setString(1, UnweightedGPA);
      preparedStmt.setString(3, TOEFLScore);
      preparedStmt.setString(4, SATScore);
      preparedStmt.setString(5, IBScore);
      preparedStmt.setString(6, StudentID.getText());
      
        preparedStmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Changed");
        
        
    } catch (SQLException ex) {
        Logger.getLogger(GPA_Yes.class.getName()).log(Level.SEVERE, null, ex);
       
    }
DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
        model.fireTableDataChanged();
        model.setRowCount(0);
        Show_Users_In_JTable();
// TODO add your handling code here:
    }//GEN-LAST:event_Update_ButtonActionPerformed

    private void AP_Yes_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AP_Yes_ButtonActionPerformed
        this.show();
        AP_Yes frm=new AP_Yes();
        frm.setVisible(true);
    }//GEN-LAST:event_AP_Yes_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Academics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Academics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Academics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Academics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new Academics().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APGrades_Label;
    private javax.swing.JLabel APGrades_Label1;
    private javax.swing.JLabel APGrades_Label2;
    private javax.swing.JLabel APGrades_Label3;
    private javax.swing.JToggleButton AP_Yes_Button;
    private javax.swing.JLabel AcademicsPage_Label;
    private javax.swing.JLabel Exit;
    private javax.swing.JToggleButton GPA_Yes_Button;
    private javax.swing.JLabel GoBack_Label;
    private javax.swing.JToggleButton IB_Yes_Button;
    private javax.swing.JToggleButton Next_Button;
    private javax.swing.JLabel SATScore_Label;
    private javax.swing.JToggleButton SAT_Yes_Button;
    private javax.swing.JToggleButton SearchAll_Button;
    protected static javax.swing.JTextField StudentID;
    public static javax.swing.JTable StudentTable;
    private javax.swing.JLabel TOEFLScore_Label;
    private javax.swing.JToggleButton TOEFL_Yes_Button;
    private javax.swing.JToggleButton Update_Button;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
