package main;
import java.awt.Color;
import static java.awt.Color.*;
import java.awt.Component;
import java.awt.event.*;
import java.sql.*;
import java.text.*;
import javax.swing.*;
import java.util.*;
import java.util.regex.*;
import static jdk.internal.org.objectweb.asm.commons.GeneratorAdapter.AND;
/**
 *
 * @author Ritik 
 */
public class Budget extends javax.swing.JFrame 
{
/**
* Creates new form Home_Data
*/
    public Budget() 
    {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        AcademicsPage_Label = new javax.swing.JLabel();
        GoBack_Label = new javax.swing.JLabel();
        Budget_ComboBox = new javax.swing.JComboBox<>();
        Heading1_Label = new javax.swing.JLabel();
        SaveBudget_Button = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });

        AcademicsPage_Label.setFont(new java.awt.Font("Raleway ExtraBold", 1, 24)); // NOI18N
        AcademicsPage_Label.setForeground(new java.awt.Color(255, 255, 255));
        AcademicsPage_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AcademicsPage_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Books_48px.png"))); // NOI18N
        AcademicsPage_Label.setText("Budget");

        GoBack_Label.setBackground(new java.awt.Color(255, 255, 255));
        GoBack_Label.setForeground(new java.awt.Color(255, 255, 255));
        GoBack_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Long_Arrow_Left_48px_2.png"))); // NOI18N
        GoBack_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GoBack_LabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GoBack_Label)
                    .addComponent(AcademicsPage_Label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AcademicsPage_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoBack_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Budget_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        Budget_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        Budget_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Choose", "$20000 - $30000", "$30000 - $40000", "$40000 - $50000", "$50000 - $60000", "$60000 - $70000", "$70000 - $80000" }));
        Budget_ComboBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Budget_ComboBoxAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Budget_ComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Budget_ComboBoxMouseClicked(evt);
            }
        });
        Budget_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Budget_ComboBoxActionPerformed(evt);
            }
        });

        Heading1_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        Heading1_Label.setForeground(new java.awt.Color(45, 118, 232));
        Heading1_Label.setText("Please choose the range of your budget:");

        SaveBudget_Button.setFont(new java.awt.Font("Raleway SemiBold", 3, 12)); // NOI18N
        SaveBudget_Button.setText("Save");
        SaveBudget_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBudget_ButtonMouseClicked(evt);
            }
        });
        SaveBudget_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBudget_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveBudget_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Heading1_Label)
                    .addComponent(Budget_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Heading1_Label)
                .addGap(0, 0, 0)
                .addComponent(Budget_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(SaveBudget_Button)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
    this.hide(); //Hides the IB_Yes jFrame and turns back to the Academics jFrame
    }//GEN-LAST:event_ExitMousePressed

    private void GoBack_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBack_LabelMousePressed
    this.hide();
     Academics frm=new Academics();
      frm.setVisible(true);
    }//GEN-LAST:event_GoBack_LabelMousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
     int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
       this.setLocation(x - xx, y - xy);       
    }//GEN-LAST:event_jPanel2MouseDragged
    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
    xx = evt.getX();
     xy = evt.getY();   
    }//GEN-LAST:event_jPanel2MousePressed

    private void Budget_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Budget_ComboBoxActionPerformed

    }//GEN-LAST:event_Budget_ComboBoxActionPerformed

    private void Budget_ComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Budget_ComboBoxMouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_Budget_ComboBoxMouseClicked

    private void SaveBudget_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBudget_ButtonMouseClicked

    }//GEN-LAST:event_SaveBudget_ButtonMouseClicked

    private void Budget_ComboBoxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Budget_ComboBoxAncestorAdded

    }//GEN-LAST:event_Budget_ComboBoxAncestorAdded

    private void SaveBudget_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBudget_ButtonActionPerformed
this.hide();
Field frm=new Field();
frm.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_SaveBudget_ButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Budget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Budget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Budget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Budget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Budget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcademicsPage_Label;
    public static javax.swing.JComboBox<String> Budget_ComboBox;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel GoBack_Label;
    private javax.swing.JLabel Heading1_Label;
    private javax.swing.JToggleButton SaveBudget_Button;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}