/**********************************************
*Personal Code: fsn821                        *
*School: Gandhi Memorial International School *
*Program Name: CollegeManager                 *
*Purpose: To make college-finding easier      *
*based on the student grades and price/field  *
**********************************************/
package main;

import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;


/**
 *
 * @author Sandeep
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SubTitle_jLabel = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Logo_jLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Academics_jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Academics_jLabel = new javax.swing.JLabel();
        FieldandBudget_jPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        FieldandBudget_jLabel = new javax.swing.JLabel();
        CollegeList_jPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CollegeList_jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(854, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        SubTitle_jLabel.setFont(new java.awt.Font("Raleway ExtraBold", 0, 10)); // NOI18N
        SubTitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        SubTitle_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubTitle_jLabel.setText(" Insight to your dream college");

        Exit.setFont(new java.awt.Font("Raleway ExtraBold", 0, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Raleway ExtraBold", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("CollegeManager");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAutoscrolls(true);

        Logo_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Collage_96px.png"))); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Logo_jLabel)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SubTitle_jLabel)
                                    .addComponent(Title)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(Exit)
                .addGap(5, 5, 5)
                .addComponent(Logo_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Title)
                .addGap(0, 0, 0)
                .addComponent(SubTitle_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 240));

        Academics_jPanel.setBackground(java.awt.SystemColor.controlHighlight);
        Academics_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Academics_jPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Academics_jPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Academics_jPanelMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Home_48px_1.png"))); // NOI18N

        Academics_jLabel.setFont(new java.awt.Font("Raleway ExtraBold", 1, 12)); // NOI18N
        Academics_jLabel.setForeground(new java.awt.Color(45, 118, 232));
        Academics_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Academics_jLabel.setText("Academics");

        javax.swing.GroupLayout Academics_jPanelLayout = new javax.swing.GroupLayout(Academics_jPanel);
        Academics_jPanel.setLayout(Academics_jPanelLayout);
        Academics_jPanelLayout.setHorizontalGroup(
            Academics_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Academics_jPanelLayout.createSequentialGroup()
                .addGroup(Academics_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Academics_jPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1))
                    .addGroup(Academics_jPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Academics_jLabel)))
                .addGap(70, 70, 70))
        );
        Academics_jPanelLayout.setVerticalGroup(
            Academics_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Academics_jPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Academics_jLabel)
                .addGap(40, 40, 40))
        );

        jPanel1.add(Academics_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 160, 150));

        FieldandBudget_jPanel.setBackground(java.awt.SystemColor.controlHighlight);
        FieldandBudget_jPanel.setPreferredSize(new java.awt.Dimension(168, 149));
        FieldandBudget_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FieldandBudget_jPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FieldandBudget_jPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FieldandBudget_jPanelMousePressed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Student_Male_48px.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        FieldandBudget_jLabel.setFont(new java.awt.Font("Raleway ExtraBold", 1, 12)); // NOI18N
        FieldandBudget_jLabel.setForeground(new java.awt.Color(45, 118, 232));
        FieldandBudget_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FieldandBudget_jLabel.setText("Field and Budget");
        FieldandBudget_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout FieldandBudget_jPanelLayout = new javax.swing.GroupLayout(FieldandBudget_jPanel);
        FieldandBudget_jPanel.setLayout(FieldandBudget_jPanelLayout);
        FieldandBudget_jPanelLayout.setHorizontalGroup(
            FieldandBudget_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FieldandBudget_jPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(FieldandBudget_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FieldandBudget_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        FieldandBudget_jPanelLayout.setVerticalGroup(
            FieldandBudget_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FieldandBudget_jPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldandBudget_jLabel)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(FieldandBudget_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 160, 150));

        CollegeList_jPanel.setBackground(java.awt.SystemColor.controlHighlight);
        CollegeList_jPanel.setPreferredSize(new java.awt.Dimension(168, 149));
        CollegeList_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CollegeList_jPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CollegeList_jPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CollegeList_jPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CollegeList_jPanelMousePressed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Settings_48px.png"))); // NOI18N

        CollegeList_jLabel.setFont(new java.awt.Font("Raleway ExtraBold", 1, 12)); // NOI18N
        CollegeList_jLabel.setForeground(new java.awt.Color(45, 118, 232));
        CollegeList_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CollegeList_jLabel.setText("College List");

        javax.swing.GroupLayout CollegeList_jPanelLayout = new javax.swing.GroupLayout(CollegeList_jPanel);
        CollegeList_jPanel.setLayout(CollegeList_jPanelLayout);
        CollegeList_jPanelLayout.setHorizontalGroup(
            CollegeList_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CollegeList_jPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(CollegeList_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CollegeList_jPanelLayout.createSequentialGroup()
                        .addComponent(CollegeList_jLabel)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CollegeList_jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        CollegeList_jPanelLayout.setVerticalGroup(
            CollegeList_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CollegeList_jPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CollegeList_jLabel)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(CollegeList_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 160, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
    System.exit(0);    // TODO add your handling code here:
    }//GEN-LAST:event_ExitMousePressed

    private void Academics_jPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Academics_jPanelMouseEntered
        setColor (Academics_jPanel);// TODO add your handling code here:
    }//GEN-LAST:event_Academics_jPanelMouseEntered

    private void Academics_jPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Academics_jPanelMouseExited
        resetColor (Academics_jPanel);// TODO add your handling code here:
    }//GEN-LAST:event_Academics_jPanelMouseExited

    private void FieldandBudget_jPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldandBudget_jPanelMouseEntered
        setColor (FieldandBudget_jPanel);// TODO add your handling code here:
    }//GEN-LAST:event_FieldandBudget_jPanelMouseEntered

    private void FieldandBudget_jPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldandBudget_jPanelMouseExited
        resetColor (FieldandBudget_jPanel);// TODO add your handling code here:
    }//GEN-LAST:event_FieldandBudget_jPanelMouseExited

    private void CollegeList_jPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CollegeList_jPanelMouseEntered
        setColor (CollegeList_jPanel);// TODO add your handling code here:
    }//GEN-LAST:event_CollegeList_jPanelMouseEntered

    private void CollegeList_jPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CollegeList_jPanelMouseExited
        resetColor (CollegeList_jPanel);// TODO add your handling code here:
    }//GEN-LAST:event_CollegeList_jPanelMouseExited

    private void Academics_jPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Academics_jPanelMousePressed
this.hide();
Academics frm=new Academics();
frm.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_Academics_jPanelMousePressed

    private void FieldandBudget_jPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldandBudget_jPanelMousePressed
this.hide();
Budget frm=new Budget();
frm.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_FieldandBudget_jPanelMousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
     int x = evt.getXOnScreen();
int y = evt.getYOnScreen();
this.setLocation(x - xx, y - xy);   // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged
int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
     xx = evt.getX();
     xy = evt.getY();   // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    private void CollegeList_jPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CollegeList_jPanelMousePressed
this.hide();
UniversityList frm=new UniversityList();
frm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_CollegeList_jPanelMousePressed

    private void CollegeList_jPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CollegeList_jPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CollegeList_jPanelMouseClicked


public void setColor(JPanel panel)
{
panel.setBackground(new java.awt.Color(255, 153, 153));
}

public void resetColor(JPanel panel)
{
panel.setBackground(new java.awt.Color(240, 240, 240));
}
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Academics_jLabel;
    private javax.swing.JPanel Academics_jPanel;
    private javax.swing.JLabel CollegeList_jLabel;
    private javax.swing.JPanel CollegeList_jPanel;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel FieldandBudget_jLabel;
    private javax.swing.JPanel FieldandBudget_jPanel;
    private javax.swing.JLabel Logo_jLabel;
    private javax.swing.JLabel SubTitle_jLabel;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
