package main;
import java.sql.*;
import java.lang.Math;

/**
 *
 * @author Ritik 
 */
public class SAT_Yes extends javax.swing.JFrame 
{
    
/**
* Creates new form Home_Data
*/
    public SAT_Yes() 
    {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel2 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        AcademicsPage_Label = new javax.swing.JLabel();
        GoBack_Label = new javax.swing.JLabel();
        SATTestsNumber_ComboBox = new javax.swing.JComboBox<>();
        Heading_Label = new javax.swing.JLabel();
        Heading3_Label = new javax.swing.JLabel();
        Heading2_Label = new javax.swing.JLabel();
        SATSubjectTestsNumber_ComboBox = new javax.swing.JComboBox<>();
        Heading4_Label = new javax.swing.JLabel();
        FirstSATII_ComboBox = new javax.swing.JComboBox<>();
        SecondSATII_ComboBox = new javax.swing.JComboBox<>();
        SecondSATIIMark_ComboBox = new javax.swing.JComboBox<>();
        FirstSATIIMark_ComboBox = new javax.swing.JComboBox<>();
        ThirdSATII_ComboBox = new javax.swing.JComboBox<>();
        FourthSATII_ComboBox = new javax.swing.JComboBox<>();
        ThirdSATIIMark_ComboBox = new javax.swing.JComboBox<>();
        CalculateSATScores_Button = new javax.swing.JToggleButton();
        FirstEnglish_ComboBox = new javax.swing.JComboBox<>();
        FirstMathematics_ComboBox = new javax.swing.JComboBox<>();
        FirstMathematicsMark_ComboBox = new javax.swing.JComboBox<>();
        FirstEnglishMark_ComboBox = new javax.swing.JComboBox<>();
        SecondEnglish_ComboBox = new javax.swing.JComboBox<>();
        SecondMathematics_ComboBox = new javax.swing.JComboBox<>();
        SecondMathematicsMark_ComboBox = new javax.swing.JComboBox<>();
        SecondEnglishMark_ComboBox = new javax.swing.JComboBox<>();
        ThirdEnglish_ComboBox = new javax.swing.JComboBox<>();
        ThirdMathematics_ComboBox = new javax.swing.JComboBox<>();
        ThirdEnglishMark_ComboBox = new javax.swing.JComboBox<>();
        ThirdMathematicsMark_ComboBox = new javax.swing.JComboBox<>();
        FourthSATIIMark_ComboBox = new javax.swing.JComboBox<>();
        SATScore1_TextField = new javax.swing.JTextField();
        SATScore1_Label = new javax.swing.JLabel();
        SATScore2_TextField = new javax.swing.JTextField();
        SATScore2_Label = new javax.swing.JLabel();
        SATScore3_Label = new javax.swing.JLabel();
        SATScore3_TextField = new javax.swing.JTextField();
        SATSuperscore_Label = new javax.swing.JLabel();
        SATSuperscore_TextField = new javax.swing.JTextField();
        HighestEnglish_Label = new javax.swing.JLabel();
        HighestEnglishScore_TextField = new javax.swing.JTextField();
        HighestMathScore_TextField = new javax.swing.JTextField();
        HighestMath_Label = new javax.swing.JLabel();
        SaveSATScores_Button1 = new javax.swing.JToggleButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });

        AcademicsPage_Label.setFont(new java.awt.Font("Raleway ExtraBold", 1, 24)); // NOI18N
        AcademicsPage_Label.setForeground(new java.awt.Color(255, 255, 255));
        AcademicsPage_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AcademicsPage_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Books_48px.png"))); // NOI18N
        AcademicsPage_Label.setText("SAT/SAT Subject Test Scores");

        GoBack_Label.setBackground(new java.awt.Color(255, 255, 255));
        GoBack_Label.setForeground(new java.awt.Color(255, 255, 255));
        GoBack_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Long_Arrow_Left_48px_2.png"))); // NOI18N
        GoBack_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GoBack_LabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GoBack_Label)
                    .addComponent(AcademicsPage_Label))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AcademicsPage_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoBack_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SATTestsNumber_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        SATTestsNumber_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        SATTestsNumber_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        SATTestsNumber_ComboBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SATTestsNumber_ComboBoxAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        SATTestsNumber_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SATTestsNumber_ComboBoxActionPerformed(evt);
            }
        });

        Heading_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        Heading_Label.setForeground(new java.awt.Color(45, 118, 232));
        Heading_Label.setText("Please choose the number of SAT Test(s) taken:");

        Heading3_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        Heading3_Label.setForeground(new java.awt.Color(45, 118, 232));
        Heading3_Label.setText("Please enter the SAT Tests and Mark(s):");

        Heading2_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        Heading2_Label.setForeground(new java.awt.Color(45, 118, 232));
        Heading2_Label.setText("Please choose the number of SAT Subject Test(s) taken:");

        SATSubjectTestsNumber_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        SATSubjectTestsNumber_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        SATSubjectTestsNumber_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        SATSubjectTestsNumber_ComboBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SATSubjectTestsNumber_ComboBoxAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        SATSubjectTestsNumber_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SATSubjectTestsNumber_ComboBoxActionPerformed(evt);
            }
        });

        Heading4_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        Heading4_Label.setForeground(new java.awt.Color(45, 118, 232));
        Heading4_Label.setText("Please enter the SAT Subject Tests and Mark(s):");

        FirstSATII_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        FirstSATII_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        FirstSATII_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose the Subject...", "Korean with Listening", "Chinese with Listening", "Italian", "Japanese with Listening", "Mathematics Level 2", "Physics", "Chemistry", "French with Listening", "Spanish with Listening", "Spanish", "United States History", "German", "French", "German with Listening", "Mathematics Level 1", "Literature", "World History", "Latin", "Modern Hebrew", "Biology E", "Biology M" }));
        FirstSATII_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstSATII_ComboBoxActionPerformed(evt);
            }
        });

        SecondSATII_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        SecondSATII_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        SecondSATII_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose the Subject...", "Korean with Listening", "Chinese with Listening", "Italian", "Japanese with Listening", "Mathematics Level 2", "Physics", "Chemistry", "French with Listening", "Spanish with Listening", "Spanish", "United States History", "German", "French", "German with Listening", "Mathematics Level 1", "Literature", "World History", "Latin", "Modern Hebrew", "Biology E", "Biology M" }));
        SecondSATII_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondSATII_ComboBoxActionPerformed(evt);
            }
        });

        SecondSATIIMark_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        SecondSATIIMark_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        SecondSATIIMark_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360", "370", "380", "390", "400", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "510", "520", "530", "540", "550", "560", "570", "580", "590", "600", "610", "620", "630", "640", "650", "660", "670", "680", "690", "700", "710", "720", "730", "740", "750", "760", "770", "780", "790", "800" }));

        FirstSATIIMark_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        FirstSATIIMark_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        FirstSATIIMark_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360", "370", "380", "390", "400", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "510", "520", "530", "540", "550", "560", "570", "580", "590", "600", "610", "620", "630", "640", "650", "660", "670", "680", "690", "700", "710", "720", "730", "740", "750", "760", "770", "780", "790", "800" }));
        FirstSATIIMark_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstSATIIMark_ComboBoxActionPerformed(evt);
            }
        });

        ThirdSATII_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        ThirdSATII_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        ThirdSATII_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose the Subject...", "Korean with Listening", "Chinese with Listening", "Italian", "Japanese with Listening", "Mathematics Level 2", "Physics", "Chemistry", "French with Listening", "Spanish with Listening", "Spanish", "United States History", "German", "French", "German with Listening", "Mathematics Level 1", "Literature", "World History", "Latin", "Modern Hebrew", "Biology E", "Biology M" }));
        ThirdSATII_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirdSATII_ComboBoxActionPerformed(evt);
            }
        });

        FourthSATII_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        FourthSATII_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        FourthSATII_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose the Subject...", "Korean with Listening", "Chinese with Listening", "Italian", "Japanese with Listening", "Mathematics Level 2", "Physics", "Chemistry", "French with Listening", "Spanish with Listening", "Spanish", "United States History", "German", "French", "German with Listening", "Mathematics Level 1", "Literature", "World History", "Latin", "Modern Hebrew", "Biology E", "Biology M" }));
        FourthSATII_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourthSATII_ComboBoxActionPerformed(evt);
            }
        });

        ThirdSATIIMark_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        ThirdSATIIMark_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        ThirdSATIIMark_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360", "370", "380", "390", "400", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "510", "520", "530", "540", "550", "560", "570", "580", "590", "600", "610", "620", "630", "640", "650", "660", "670", "680", "690", "700", "710", "720", "730", "740", "750", "760", "770", "780", "790", "800" }));
        ThirdSATIIMark_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirdSATIIMark_ComboBoxActionPerformed(evt);
            }
        });

        CalculateSATScores_Button.setFont(new java.awt.Font("Raleway SemiBold", 3, 12)); // NOI18N
        CalculateSATScores_Button.setText("Calculate");
        CalculateSATScores_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculateSATScores_ButtonMouseClicked(evt);
            }
        });
        CalculateSATScores_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateSATScores_ButtonActionPerformed(evt);
            }
        });

        FirstEnglish_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        FirstEnglish_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        FirstEnglish_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English" }));

        FirstMathematics_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        FirstMathematics_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        FirstMathematics_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mathematics" }));

        FirstMathematicsMark_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        FirstMathematicsMark_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        FirstMathematicsMark_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360", "370", "380", "390", "400", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "510", "520", "530", "540", "550", "560", "570", "580", "590", "600", "610", "620", "630", "640", "650", "660", "670", "680", "690", "700", "710", "720", "730", "740", "750", "760", "770", "780", "790", "800" }));

        FirstEnglishMark_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        FirstEnglishMark_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        FirstEnglishMark_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360", "370", "380", "390", "400", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "510", "520", "530", "540", "550", "560", "570", "580", "590", "600", "610", "620", "630", "640", "650", "660", "670", "680", "690", "700", "710", "720", "730", "740", "750", "760", "770", "780", "790", "800" }));

        SecondEnglish_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        SecondEnglish_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        SecondEnglish_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English" }));

        SecondMathematics_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        SecondMathematics_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        SecondMathematics_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mathematics" }));

        SecondMathematicsMark_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        SecondMathematicsMark_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        SecondMathematicsMark_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360", "370", "380", "390", "400", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "510", "520", "530", "540", "550", "560", "570", "580", "590", "600", "610", "620", "630", "640", "650", "660", "670", "680", "690", "700", "710", "720", "730", "740", "750", "760", "770", "780", "790", "800" }));

        SecondEnglishMark_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        SecondEnglishMark_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        SecondEnglishMark_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360", "370", "380", "390", "400", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "510", "520", "530", "540", "550", "560", "570", "580", "590", "600", "610", "620", "630", "640", "650", "660", "670", "680", "690", "700", "710", "720", "730", "740", "750", "760", "770", "780", "790", "800" }));

        ThirdEnglish_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        ThirdEnglish_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        ThirdEnglish_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English" }));

        ThirdMathematics_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        ThirdMathematics_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        ThirdMathematics_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mathematics" }));

        ThirdEnglishMark_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        ThirdEnglishMark_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        ThirdEnglishMark_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360", "370", "380", "390", "400", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "510", "520", "530", "540", "550", "560", "570", "580", "590", "600", "610", "620", "630", "640", "650", "660", "670", "680", "690", "700", "710", "720", "730", "740", "750", "760", "770", "780", "790", "800" }));

        ThirdMathematicsMark_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        ThirdMathematicsMark_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        ThirdMathematicsMark_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360", "370", "380", "390", "400", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "510", "520", "530", "540", "550", "560", "570", "580", "590", "600", "610", "620", "630", "640", "650", "660", "670", "680", "690", "700", "710", "720", "730", "740", "750", "760", "770", "780", "790", "800" }));

        FourthSATIIMark_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        FourthSATIIMark_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        FourthSATIIMark_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360", "370", "380", "390", "400", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "510", "520", "530", "540", "550", "560", "570", "580", "590", "600", "610", "620", "630", "640", "650", "660", "670", "680", "690", "700", "710", "720", "730", "740", "750", "760", "770", "780", "790", "800" }));
        FourthSATIIMark_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourthSATIIMark_ComboBoxActionPerformed(evt);
            }
        });

        SATScore1_TextField.setEditable(false);
        SATScore1_TextField.setBackground(new java.awt.Color(214, 217, 223));
        SATScore1_TextField.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        SATScore1_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SATScore1_TextField.setBorder(null);
        SATScore1_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SATScore1_TextFieldActionPerformed(evt);
            }
        });

        SATScore1_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        SATScore1_Label.setText("Total SAT Score:");

        SATScore2_TextField.setEditable(false);
        SATScore2_TextField.setBackground(new java.awt.Color(214, 217, 223));
        SATScore2_TextField.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        SATScore2_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SATScore2_TextField.setBorder(null);

        SATScore2_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        SATScore2_Label.setText("Total SAT Score:");

        SATScore3_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        SATScore3_Label.setText("Total SAT Score:");

        SATScore3_TextField.setEditable(false);
        SATScore3_TextField.setBackground(new java.awt.Color(214, 217, 223));
        SATScore3_TextField.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        SATScore3_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SATScore3_TextField.setBorder(null);
        SATScore3_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SATScore3_TextFieldActionPerformed(evt);
            }
        });

        SATSuperscore_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        SATSuperscore_Label.setText("SAT Superscore:");

        SATSuperscore_TextField.setEditable(false);
        SATSuperscore_TextField.setBackground(new java.awt.Color(214, 217, 223));
        SATSuperscore_TextField.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        SATSuperscore_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SATSuperscore_TextField.setBorder(null);

        HighestEnglish_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        HighestEnglish_Label.setForeground(new java.awt.Color(255, 0, 51));
        HighestEnglish_Label.setText("Highest English:");

        HighestEnglishScore_TextField.setEditable(false);
        HighestEnglishScore_TextField.setBackground(new java.awt.Color(214, 217, 223));
        HighestEnglishScore_TextField.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        HighestEnglishScore_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HighestEnglishScore_TextField.setBorder(null);
        HighestEnglishScore_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighestEnglishScore_TextFieldActionPerformed(evt);
            }
        });

        HighestMathScore_TextField.setEditable(false);
        HighestMathScore_TextField.setBackground(new java.awt.Color(214, 217, 223));
        HighestMathScore_TextField.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        HighestMathScore_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HighestMathScore_TextField.setBorder(null);

        HighestMath_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        HighestMath_Label.setForeground(new java.awt.Color(255, 0, 51));
        HighestMath_Label.setText("Highest Math:");

        SaveSATScores_Button1.setFont(new java.awt.Font("Raleway SemiBold", 3, 12)); // NOI18N
        SaveSATScores_Button1.setText("Save");
        SaveSATScores_Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveSATScores_Button1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FirstSATII_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SecondSATII_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FirstSATIIMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SecondSATIIMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FourthSATII_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ThirdSATII_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FourthSATIIMark_ComboBox, 0, 60, Short.MAX_VALUE)
                            .addComponent(ThirdSATIIMark_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(Heading4_Label)
                    .addComponent(Heading2_Label)
                    .addComponent(Heading_Label)
                    .addComponent(SATTestsNumber_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Heading3_Label)
                    .addComponent(SATSubjectTestsNumber_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(FirstEnglish_ComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FirstMathematics_ComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(FirstMathematicsMark_ComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SATScore1_TextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstEnglishMark_ComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 66, Short.MAX_VALUE)))
                            .addComponent(SATScore1_Label)
                            .addComponent(CalculateSATScores_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HighestEnglish_Label)
                                    .addComponent(HighestMath_Label)
                                    .addComponent(SATSuperscore_Label, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HighestMathScore_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SATSuperscore_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HighestEnglishScore_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SecondEnglish_ComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SecondMathematics_ComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SATScore2_Label, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SATScore2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SecondEnglishMark_ComboBox, 0, 62, Short.MAX_VALUE)
                                    .addComponent(SecondMathematicsMark_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SATScore3_Label, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ThirdEnglish_ComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ThirdMathematics_ComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 120, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SATScore3_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ThirdEnglishMark_ComboBox, 0, 66, Short.MAX_VALUE)
                                    .addComponent(ThirdMathematicsMark_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(SaveSATScores_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(666, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Heading_Label)
                .addGap(0, 0, 0)
                .addComponent(SATTestsNumber_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Heading2_Label)
                .addGap(0, 0, 0)
                .addComponent(SATSubjectTestsNumber_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Heading3_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstEnglish_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstEnglishMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstMathematics_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstMathematicsMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SecondEnglish_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SecondEnglishMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SecondMathematics_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SecondMathematicsMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ThirdEnglish_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThirdEnglishMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ThirdMathematics_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThirdMathematicsMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SATScore1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SATScore2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SATScore3_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SATScore3_Label))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SATScore1_Label)
                        .addComponent(SATScore2_Label)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HighestEnglishScore_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HighestEnglish_Label))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HighestMathScore_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HighestMath_Label))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SATSuperscore_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SATSuperscore_Label))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CalculateSATScores_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(Heading4_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ThirdSATIIMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FirstSATII_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FirstSATIIMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, 0)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SecondSATII_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SecondSATIIMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(ThirdSATII_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FourthSATII_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FourthSATIIMark_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(628, Short.MAX_VALUE)
                    .addComponent(SaveSATScores_Button1)
                    .addGap(16, 16, 16)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
    this.hide(); //Hides the IB_Yes jFrame and turns back to the Academics jFrame
    }//GEN-LAST:event_ExitMousePressed

    private void GoBack_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBack_LabelMousePressed
    this.hide();
     Academics frm=new Academics();
      frm.setVisible(true);
    }//GEN-LAST:event_GoBack_LabelMousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
     int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
       this.setLocation(x - xx, y - xy);       
    }//GEN-LAST:event_jPanel2MouseDragged
    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
    xx = evt.getX();
     xy = evt.getY();   
    }//GEN-LAST:event_jPanel2MousePressed

    private void SATTestsNumber_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SATTestsNumber_ComboBoxActionPerformed
if (SATTestsNumber_ComboBox.getSelectedIndex() == 1){
FirstEnglish_ComboBox.setVisible(true);
FirstEnglishMark_ComboBox.setVisible(true);
SecondEnglish_ComboBox.setVisible(false);
SecondEnglishMark_ComboBox.setVisible(false);
ThirdEnglish_ComboBox.setVisible(false);
ThirdEnglishMark_ComboBox.setVisible(false);
FirstMathematics_ComboBox.setVisible(true);
FirstMathematicsMark_ComboBox.setVisible(true);
SecondMathematics_ComboBox.setVisible(false);
SecondMathematicsMark_ComboBox.setVisible(false);
ThirdMathematics_ComboBox.setVisible(false);
ThirdMathematicsMark_ComboBox.setVisible(false);
SATScore1_Label.setVisible(true);
SATScore1_TextField.setVisible(true);
SATScore2_Label.setVisible(false);
SATScore2_TextField.setVisible(false);
SATScore3_Label.setVisible(false);
SATScore3_TextField.setVisible(false);
SATSuperscore_Label.setVisible(false);
SATSuperscore_TextField.setVisible(false);
HighestEnglish_Label.setVisible(false);
HighestEnglishScore_TextField.setVisible(false);
HighestMath_Label.setVisible(false);
HighestMathScore_TextField.setVisible(false);
CalculateSATScores_Button.setVisible(true);
Heading3_Label.setVisible(true);
}
if (SATTestsNumber_ComboBox.getSelectedIndex() == 2){
  FirstEnglish_ComboBox.setVisible(true);
FirstEnglishMark_ComboBox.setVisible(true);
SecondEnglish_ComboBox.setVisible(true);
SecondEnglishMark_ComboBox.setVisible(true);
ThirdEnglish_ComboBox.setVisible(false);
ThirdEnglishMark_ComboBox.setVisible(false);
FirstMathematics_ComboBox.setVisible(true);
FirstMathematicsMark_ComboBox.setVisible(true);
SecondMathematics_ComboBox.setVisible(true);
SecondMathematicsMark_ComboBox.setVisible(true);
ThirdMathematics_ComboBox.setVisible(false);
ThirdMathematicsMark_ComboBox.setVisible(false); 
SATScore1_Label.setVisible(true);
SATScore1_TextField.setVisible(true);
SATScore2_Label.setVisible(true);
SATScore2_TextField.setVisible(true);
SATScore3_Label.setVisible(false);
SATScore3_TextField.setVisible(false);
SATSuperscore_Label.setVisible(true);
SATSuperscore_TextField.setVisible(true);
HighestEnglish_Label.setVisible(true);
HighestEnglishScore_TextField.setVisible(true);
HighestMath_Label.setVisible(true);
HighestMathScore_TextField.setVisible(true);
CalculateSATScores_Button.setVisible(true);
Heading3_Label.setVisible(true);
}
if (SATTestsNumber_ComboBox.getSelectedIndex() == 3){
FirstEnglish_ComboBox.setVisible(true);
FirstEnglishMark_ComboBox.setVisible(true);
SecondEnglish_ComboBox.setVisible(true);
SecondEnglishMark_ComboBox.setVisible(true);
ThirdEnglish_ComboBox.setVisible(true);
ThirdEnglishMark_ComboBox.setVisible(true);
FirstMathematics_ComboBox.setVisible(true);
FirstMathematicsMark_ComboBox.setVisible(true);
SecondMathematics_ComboBox.setVisible(true);
SecondMathematicsMark_ComboBox.setVisible(true);
ThirdMathematics_ComboBox.setVisible(true);
ThirdMathematicsMark_ComboBox.setVisible(true);
SATScore1_Label.setVisible(true);
SATScore1_TextField.setVisible(true);
SATScore2_Label.setVisible(true);
SATScore2_TextField.setVisible(true);
SATScore3_Label.setVisible(true);
SATScore3_TextField.setVisible(true);
SATSuperscore_Label.setVisible(true);
SATSuperscore_TextField.setVisible(true);
HighestEnglish_Label.setVisible(true);
HighestEnglishScore_TextField.setVisible(true);
HighestMath_Label.setVisible(true);
HighestMathScore_TextField.setVisible(true);
CalculateSATScores_Button.setVisible(true);
Heading3_Label.setVisible(true);
}

    }//GEN-LAST:event_SATTestsNumber_ComboBoxActionPerformed

    private void SATSubjectTestsNumber_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SATSubjectTestsNumber_ComboBoxActionPerformed
if (SATSubjectTestsNumber_ComboBox.getSelectedIndex() == 0){
     FirstSATII_ComboBox.setVisible(false);
     SecondSATII_ComboBox.setVisible(false);
     ThirdSATII_ComboBox.setVisible(false);
     FourthSATII_ComboBox.setVisible(false);
     FirstSATIIMark_ComboBox.setVisible(false);
     SecondSATIIMark_ComboBox.setVisible(false);
     ThirdSATIIMark_ComboBox.setVisible(false);
     FourthSATIIMark_ComboBox.setVisible(false);
        Heading4_Label.setVisible(false);
}if (SATSubjectTestsNumber_ComboBox.getSelectedIndex() == 1){
     FirstSATII_ComboBox.setVisible(true);
     SecondSATII_ComboBox.setVisible(false);
     ThirdSATII_ComboBox.setVisible(false);
        FourthSATII_ComboBox.setVisible(false);
          ThirdSATII_ComboBox.setVisible(false);
           FourthSATII_ComboBox.setVisible(false);
              FirstSATIIMark_ComboBox.setVisible(true);
             SecondSATIIMark_ComboBox.setVisible(false);
            ThirdSATIIMark_ComboBox.setVisible(false);
           FourthSATIIMark_ComboBox.setVisible(false);
        ThirdSATIIMark_ComboBox.setVisible(false);
        Heading4_Label.setVisible(true);
}
if (SATSubjectTestsNumber_ComboBox.getSelectedIndex() == 2){
     SecondSATII_ComboBox.setVisible(true);
      FirstSATII_ComboBox.setVisible(true);
       ThirdSATII_ComboBox.setVisible(false);
        FourthSATII_ComboBox.setVisible(false);
        ThirdSATII_ComboBox.setVisible(false);
           FourthSATII_ComboBox.setVisible(false);
           FirstSATIIMark_ComboBox.setVisible(true);
             SecondSATIIMark_ComboBox.setVisible(true);
            ThirdSATIIMark_ComboBox.setVisible(false);
           FourthSATIIMark_ComboBox.setVisible(false);
           ThirdSATIIMark_ComboBox.setVisible(false);
           Heading4_Label.setVisible(true);
}
if (SATSubjectTestsNumber_ComboBox.getSelectedIndex() == 3){
     FirstSATII_ComboBox.setVisible(true);
     SecondSATII_ComboBox.setVisible(true);
     ThirdSATII_ComboBox.setVisible(true);
     FourthSATII_ComboBox.setVisible(false);
     FirstSATIIMark_ComboBox.setVisible(true);
     SecondSATIIMark_ComboBox.setVisible(true);
     ThirdSATIIMark_ComboBox.setVisible(true);
     FourthSATIIMark_ComboBox.setVisible(false);
     Heading4_Label.setVisible(true);
}
if (SATSubjectTestsNumber_ComboBox.getSelectedIndex() == 4){
     FirstSATII_ComboBox.setVisible(true);
     SecondSATII_ComboBox.setVisible(true);
     ThirdSATII_ComboBox.setVisible(true);
     FourthSATII_ComboBox.setVisible(true);
     FirstSATIIMark_ComboBox.setVisible(true);
     SecondSATIIMark_ComboBox.setVisible(true);
     ThirdSATIIMark_ComboBox.setVisible(true);
     FourthSATIIMark_ComboBox.setVisible(true);
        Heading4_Label.setVisible(true);
}
    }//GEN-LAST:event_SATSubjectTestsNumber_ComboBoxActionPerformed

    private void FirstSATII_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstSATII_ComboBoxActionPerformed
if(FirstSATII_ComboBox.getSelectedIndex()>0)
{
    FirstSATII_ComboBox.setEnabled(false);
    SecondSATII_ComboBox.removeItemAt(FirstSATII_ComboBox.getSelectedIndex());
    ThirdSATII_ComboBox.removeItemAt(FirstSATII_ComboBox.getSelectedIndex());
    FourthSATII_ComboBox.removeItemAt(FirstSATII_ComboBox.getSelectedIndex());
}        
    }//GEN-LAST:event_FirstSATII_ComboBoxActionPerformed

    private void SecondSATII_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondSATII_ComboBoxActionPerformed
if(SecondSATII_ComboBox.getSelectedIndex()>0)
{
    SecondSATII_ComboBox.setEnabled(false);
    FirstSATII_ComboBox.removeItemAt(SecondSATII_ComboBox.getSelectedIndex());
    ThirdSATII_ComboBox.removeItemAt(SecondSATII_ComboBox.getSelectedIndex());
    FourthSATII_ComboBox.removeItemAt(SecondSATII_ComboBox.getSelectedIndex());
}        // TODO add your handling code here:
    }//GEN-LAST:event_SecondSATII_ComboBoxActionPerformed

    private void FirstSATIIMark_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstSATIIMark_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstSATIIMark_ComboBoxActionPerformed

    private void ThirdSATII_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirdSATII_ComboBoxActionPerformed
if(ThirdSATII_ComboBox.getSelectedIndex()>0)
{
    ThirdSATII_ComboBox.setEnabled(false);
    SecondSATII_ComboBox.removeItemAt(ThirdSATII_ComboBox.getSelectedIndex());
    FirstSATII_ComboBox.removeItemAt(ThirdSATII_ComboBox.getSelectedIndex());
    FourthSATII_ComboBox.removeItemAt(ThirdSATII_ComboBox.getSelectedIndex());
}        // TODO add your handling code here:
    }//GEN-LAST:event_ThirdSATII_ComboBoxActionPerformed

    private void FourthSATII_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourthSATII_ComboBoxActionPerformed
if(FourthSATII_ComboBox.getSelectedIndex()>0)
{
    FourthSATII_ComboBox.setEnabled(false);
    SecondSATII_ComboBox.removeItemAt(FourthSATII_ComboBox.getSelectedIndex());
    ThirdSATII_ComboBox.removeItemAt(FourthSATII_ComboBox.getSelectedIndex());
    FirstSATII_ComboBox.removeItemAt(FourthSATII_ComboBox.getSelectedIndex());
}        // TODO add your handling code here:
    }//GEN-LAST:event_FourthSATII_ComboBoxActionPerformed

    private void ThirdSATIIMark_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirdSATIIMark_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThirdSATIIMark_ComboBoxActionPerformed

    private void SATTestsNumber_ComboBoxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SATTestsNumber_ComboBoxAncestorAdded
Heading3_Label.setVisible(false);
FirstEnglish_ComboBox.setVisible(false);
SecondEnglish_ComboBox.setVisible(false);
ThirdEnglish_ComboBox.setVisible(false);
FirstEnglishMark_ComboBox.setVisible(false);
SecondEnglishMark_ComboBox.setVisible(false);
ThirdEnglishMark_ComboBox.setVisible(false);
FirstMathematics_ComboBox.setVisible(false);
SecondMathematics_ComboBox.setVisible(false);
ThirdMathematics_ComboBox.setVisible(false);
FirstMathematicsMark_ComboBox.setVisible(false);
SecondMathematicsMark_ComboBox.setVisible(false);
ThirdMathematicsMark_ComboBox.setVisible(false);
SATScore1_Label.setVisible(false);
SATScore1_TextField.setVisible(false);
SATScore2_Label.setVisible(false);
SATScore2_TextField.setVisible(false);
SATScore3_Label.setVisible(false);
SATScore3_TextField.setVisible(false);
SATSuperscore_Label.setVisible(false);
SATSuperscore_TextField.setVisible(false);
HighestEnglish_Label.setVisible(false);
HighestEnglishScore_TextField.setVisible(false);
HighestMath_Label.setVisible(false);
HighestMathScore_TextField.setVisible(false);
CalculateSATScores_Button.setVisible(false);
    }//GEN-LAST:event_SATTestsNumber_ComboBoxAncestorAdded

    private void SATSubjectTestsNumber_ComboBoxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SATSubjectTestsNumber_ComboBoxAncestorAdded
Heading4_Label.setVisible(false);
FirstSATII_ComboBox.setVisible(false);
SecondSATII_ComboBox.setVisible(false);
ThirdSATII_ComboBox.setVisible(false);
FourthSATII_ComboBox.setVisible(false);
FirstSATIIMark_ComboBox.setVisible(false);
SecondSATIIMark_ComboBox.setVisible(false);
ThirdSATIIMark_ComboBox.setVisible(false);
FourthSATIIMark_ComboBox.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_SATSubjectTestsNumber_ComboBoxAncestorAdded

    private void CalculateSATScores_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculateSATScores_ButtonMouseClicked
int EnglishScore1 = 200 + (FirstEnglishMark_ComboBox.getSelectedIndex()*10);
int MathScore1 = 200 + (FirstMathematicsMark_ComboBox.getSelectedIndex()*10);
        int SATScore1 = EnglishScore1 + MathScore1;
        SATScore1_TextField.setText("" + SATScore1);
int EnglishScore2 = 200 + (SecondEnglishMark_ComboBox.getSelectedIndex()*10);
int MathScore2 = 200 + (SecondMathematicsMark_ComboBox.getSelectedIndex()*10);
        int SATScore2 = EnglishScore2 + MathScore2;
        SATScore2_TextField.setText("" + SATScore2 );
int EnglishScore3 = 200 + (ThirdEnglishMark_ComboBox.getSelectedIndex()*10);
int MathScore3 = 200 + (ThirdMathematicsMark_ComboBox.getSelectedIndex()*10);
        int SATScore3 = EnglishScore3 + MathScore3;
        SATScore3_TextField.setText("" + SATScore3 );
int HighestEnglish = Math.max(EnglishScore1, Math.max(EnglishScore2, EnglishScore3));
int HighestMath = Math.max(MathScore1, Math.max(MathScore2, MathScore3));
HighestEnglishScore_TextField.setText("" + HighestEnglish);
HighestMathScore_TextField.setText("" + HighestMath);
int SATSuperscore = HighestEnglish + HighestMath;
SATSuperscore_TextField.setText(""+ SATSuperscore);
    }//GEN-LAST:event_CalculateSATScores_ButtonMouseClicked

    private void FourthSATIIMark_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourthSATIIMark_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FourthSATIIMark_ComboBoxActionPerformed

    private void SATScore3_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SATScore3_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SATScore3_TextFieldActionPerformed

    private void SaveSATScores_Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveSATScores_Button1MouseClicked

this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_SaveSATScores_Button1MouseClicked

    private void CalculateSATScores_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateSATScores_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalculateSATScores_ButtonActionPerformed

    private void HighestEnglishScore_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighestEnglishScore_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HighestEnglishScore_TextFieldActionPerformed

    private void SATScore1_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SATScore1_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SATScore1_TextFieldActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAT_Yes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAT_Yes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAT_Yes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAT_Yes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAT_Yes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcademicsPage_Label;
    private javax.swing.JToggleButton CalculateSATScores_Button;
    private javax.swing.JLabel Exit;
    public static javax.swing.JComboBox<String> FirstEnglishMark_ComboBox;
    public static javax.swing.JComboBox<String> FirstEnglish_ComboBox;
    public static javax.swing.JComboBox<String> FirstMathematicsMark_ComboBox;
    private javax.swing.JComboBox<String> FirstMathematics_ComboBox;
    private javax.swing.JComboBox<String> FirstSATIIMark_ComboBox;
    private javax.swing.JComboBox<String> FirstSATII_ComboBox;
    private javax.swing.JComboBox<String> FourthSATIIMark_ComboBox;
    private javax.swing.JComboBox<String> FourthSATII_ComboBox;
    private javax.swing.JLabel GoBack_Label;
    private javax.swing.JLabel Heading2_Label;
    private javax.swing.JLabel Heading3_Label;
    private javax.swing.JLabel Heading4_Label;
    private javax.swing.JLabel Heading_Label;
    private javax.swing.JTextField HighestEnglishScore_TextField;
    private javax.swing.JLabel HighestEnglish_Label;
    private javax.swing.JTextField HighestMathScore_TextField;
    private javax.swing.JLabel HighestMath_Label;
    private javax.swing.JLabel SATScore1_Label;
    private javax.swing.JTextField SATScore1_TextField;
    private javax.swing.JLabel SATScore2_Label;
    private javax.swing.JTextField SATScore2_TextField;
    private javax.swing.JLabel SATScore3_Label;
    private javax.swing.JTextField SATScore3_TextField;
    private javax.swing.JComboBox<String> SATSubjectTestsNumber_ComboBox;
    private javax.swing.JLabel SATSuperscore_Label;
    public static javax.swing.JTextField SATSuperscore_TextField;
    private javax.swing.JComboBox<String> SATTestsNumber_ComboBox;
    private javax.swing.JToggleButton SaveSATScores_Button1;
    public static javax.swing.JComboBox<String> SecondEnglishMark_ComboBox;
    private javax.swing.JComboBox<String> SecondEnglish_ComboBox;
    public static javax.swing.JComboBox<String> SecondMathematicsMark_ComboBox;
    private javax.swing.JComboBox<String> SecondMathematics_ComboBox;
    private javax.swing.JComboBox<String> SecondSATIIMark_ComboBox;
    private javax.swing.JComboBox<String> SecondSATII_ComboBox;
    public static javax.swing.JComboBox<String> ThirdEnglishMark_ComboBox;
    private javax.swing.JComboBox<String> ThirdEnglish_ComboBox;
    public static javax.swing.JComboBox<String> ThirdMathematicsMark_ComboBox;
    private javax.swing.JComboBox<String> ThirdMathematics_ComboBox;
    private javax.swing.JComboBox<String> ThirdSATIIMark_ComboBox;
    private javax.swing.JComboBox<String> ThirdSATII_ComboBox;
    private javax.swing.JPanel jPanel2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}