package main;
import java.awt.Color;
import static java.awt.Color.BLUE;
import static java.awt.Color.RED;
import java.awt.Component;
import java.awt.event.*;
import java.sql.*;
import java.text.*;
import javax.swing.*;
import java.util.*;
import java.util.regex.*;
import static jdk.internal.org.objectweb.asm.commons.GeneratorAdapter.AND;
/**
 *
 * @author Ritik 
 */
public class TOEFL_Yes extends javax.swing.JFrame 
{
/**
* Creates new form Home_Data
*/
    public TOEFL_Yes() 
    {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        AcademicsPage_Label = new javax.swing.JLabel();
        GoBack_Label = new javax.swing.JLabel();
        ReadingScore_ComboBox = new javax.swing.JComboBox<>();
        Heading_Label = new javax.swing.JLabel();
        SaveAPScores_Button = new javax.swing.JToggleButton();
        ResetAPScores_Button = new javax.swing.JToggleButton();
        APCoursesNumber_ComboBox2 = new javax.swing.JComboBox<>();
        APCoursesNumber_ComboBox3 = new javax.swing.JComboBox<>();
        ListeningScore_ComboBox = new javax.swing.JComboBox<>();
        APCoursesNumber_ComboBox4 = new javax.swing.JComboBox<>();
        SpeakingScore_ComboBox = new javax.swing.JComboBox<>();
        APCoursesNumber_ComboBox6 = new javax.swing.JComboBox<>();
        WritingScore_ComboBox = new javax.swing.JComboBox<>();
        Heading_Label1 = new javax.swing.JLabel();
        TOEFLScore_TextField = new javax.swing.JTextField();
        SaveAPScores_Button1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });

        AcademicsPage_Label.setFont(new java.awt.Font("Raleway ExtraBold", 1, 24)); // NOI18N
        AcademicsPage_Label.setForeground(new java.awt.Color(255, 255, 255));
        AcademicsPage_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AcademicsPage_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Books_48px.png"))); // NOI18N
        AcademicsPage_Label.setText("TOEFL Score");

        GoBack_Label.setBackground(new java.awt.Color(255, 255, 255));
        GoBack_Label.setForeground(new java.awt.Color(255, 255, 255));
        GoBack_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Long_Arrow_Left_48px_2.png"))); // NOI18N
        GoBack_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GoBack_LabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GoBack_Label)
                    .addComponent(AcademicsPage_Label))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AcademicsPage_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoBack_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ReadingScore_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        ReadingScore_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        ReadingScore_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        ReadingScore_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ReadingScore_ComboBoxItemStateChanged(evt);
            }
        });
        ReadingScore_ComboBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ReadingScore_ComboBoxAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ReadingScore_ComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReadingScore_ComboBoxMouseClicked(evt);
            }
        });
        ReadingScore_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadingScore_ComboBoxActionPerformed(evt);
            }
        });

        Heading_Label.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        Heading_Label.setForeground(new java.awt.Color(45, 118, 232));
        Heading_Label.setText("Please input your TOEFL Score:");

        SaveAPScores_Button.setFont(new java.awt.Font("Raleway SemiBold", 3, 12)); // NOI18N
        SaveAPScores_Button.setText("Save");
        SaveAPScores_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveAPScores_ButtonMouseClicked(evt);
            }
        });
        SaveAPScores_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAPScores_ButtonActionPerformed(evt);
            }
        });

        ResetAPScores_Button.setFont(new java.awt.Font("Raleway SemiBold", 3, 12)); // NOI18N
        ResetAPScores_Button.setText("Reset");
        ResetAPScores_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetAPScores_ButtonActionPerformed(evt);
            }
        });

        APCoursesNumber_ComboBox2.setBackground(new java.awt.Color(204, 102, 0));
        APCoursesNumber_ComboBox2.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        APCoursesNumber_ComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reading" }));
        APCoursesNumber_ComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                APCoursesNumber_ComboBox2ItemStateChanged(evt);
            }
        });
        APCoursesNumber_ComboBox2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                APCoursesNumber_ComboBox2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        APCoursesNumber_ComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APCoursesNumber_ComboBox2MouseClicked(evt);
            }
        });
        APCoursesNumber_ComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APCoursesNumber_ComboBox2ActionPerformed(evt);
            }
        });

        APCoursesNumber_ComboBox3.setBackground(new java.awt.Color(204, 102, 0));
        APCoursesNumber_ComboBox3.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        APCoursesNumber_ComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listening" }));
        APCoursesNumber_ComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                APCoursesNumber_ComboBox3ItemStateChanged(evt);
            }
        });
        APCoursesNumber_ComboBox3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                APCoursesNumber_ComboBox3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        APCoursesNumber_ComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APCoursesNumber_ComboBox3MouseClicked(evt);
            }
        });
        APCoursesNumber_ComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APCoursesNumber_ComboBox3ActionPerformed(evt);
            }
        });

        ListeningScore_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        ListeningScore_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        ListeningScore_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        ListeningScore_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListeningScore_ComboBoxItemStateChanged(evt);
            }
        });
        ListeningScore_ComboBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ListeningScore_ComboBoxAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ListeningScore_ComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListeningScore_ComboBoxMouseClicked(evt);
            }
        });
        ListeningScore_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeningScore_ComboBoxActionPerformed(evt);
            }
        });

        APCoursesNumber_ComboBox4.setBackground(new java.awt.Color(204, 102, 0));
        APCoursesNumber_ComboBox4.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        APCoursesNumber_ComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Speaking" }));
        APCoursesNumber_ComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                APCoursesNumber_ComboBox4ItemStateChanged(evt);
            }
        });
        APCoursesNumber_ComboBox4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                APCoursesNumber_ComboBox4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        APCoursesNumber_ComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APCoursesNumber_ComboBox4MouseClicked(evt);
            }
        });
        APCoursesNumber_ComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APCoursesNumber_ComboBox4ActionPerformed(evt);
            }
        });

        SpeakingScore_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        SpeakingScore_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        SpeakingScore_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        SpeakingScore_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SpeakingScore_ComboBoxItemStateChanged(evt);
            }
        });
        SpeakingScore_ComboBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SpeakingScore_ComboBoxAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        SpeakingScore_ComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpeakingScore_ComboBoxMouseClicked(evt);
            }
        });
        SpeakingScore_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeakingScore_ComboBoxActionPerformed(evt);
            }
        });

        APCoursesNumber_ComboBox6.setBackground(new java.awt.Color(204, 102, 0));
        APCoursesNumber_ComboBox6.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        APCoursesNumber_ComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Writing" }));
        APCoursesNumber_ComboBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                APCoursesNumber_ComboBox6ItemStateChanged(evt);
            }
        });
        APCoursesNumber_ComboBox6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                APCoursesNumber_ComboBox6AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        APCoursesNumber_ComboBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APCoursesNumber_ComboBox6MouseClicked(evt);
            }
        });
        APCoursesNumber_ComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APCoursesNumber_ComboBox6ActionPerformed(evt);
            }
        });

        WritingScore_ComboBox.setBackground(new java.awt.Color(204, 102, 0));
        WritingScore_ComboBox.setFont(new java.awt.Font("Raleway SemiBold", 2, 14)); // NOI18N
        WritingScore_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        WritingScore_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                WritingScore_ComboBoxItemStateChanged(evt);
            }
        });
        WritingScore_ComboBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                WritingScore_ComboBoxAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        WritingScore_ComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WritingScore_ComboBoxMouseClicked(evt);
            }
        });
        WritingScore_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WritingScore_ComboBoxActionPerformed(evt);
            }
        });

        Heading_Label1.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        Heading_Label1.setText("Total Score:");

        TOEFLScore_TextField.setEditable(false);
        TOEFLScore_TextField.setBackground(new java.awt.Color(214, 217, 223));
        TOEFLScore_TextField.setFont(new java.awt.Font("Raleway ExtraBold", 3, 14)); // NOI18N
        TOEFLScore_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TOEFLScore_TextField.setBorder(null);

        SaveAPScores_Button1.setFont(new java.awt.Font("Raleway SemiBold", 3, 12)); // NOI18N
        SaveAPScores_Button1.setText("Calculate");
        SaveAPScores_Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveAPScores_Button1MouseClicked(evt);
            }
        });
        SaveAPScores_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAPScores_Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveAPScores_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(APCoursesNumber_ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListeningScore_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(APCoursesNumber_ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReadingScore_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaveAPScores_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResetAPScores_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Heading_Label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Heading_Label1)
                            .addGap(18, 18, 18)
                            .addComponent(TOEFLScore_TextField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(APCoursesNumber_ComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WritingScore_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(APCoursesNumber_ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SpeakingScore_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Heading_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReadingScore_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(APCoursesNumber_ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListeningScore_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(APCoursesNumber_ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeakingScore_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(APCoursesNumber_ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WritingScore_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(APCoursesNumber_ComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Heading_Label1)
                    .addComponent(TOEFLScore_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveAPScores_Button1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveAPScores_Button)
                    .addComponent(ResetAPScores_Button))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
    this.hide(); //Hides the IB_Yes jFrame and turns back to the Academics jFrame
    }//GEN-LAST:event_ExitMousePressed

    private void GoBack_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBack_LabelMousePressed
    this.hide();
     Academics frm=new Academics();
      frm.setVisible(true);
    }//GEN-LAST:event_GoBack_LabelMousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
     int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
       this.setLocation(x - xx, y - xy);       
    }//GEN-LAST:event_jPanel2MouseDragged
    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
    xx = evt.getX();
     xy = evt.getY();   
    }//GEN-LAST:event_jPanel2MousePressed

    private void ReadingScore_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadingScore_ComboBoxActionPerformed

    }//GEN-LAST:event_ReadingScore_ComboBoxActionPerformed

    private void SaveAPScores_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAPScores_ButtonActionPerformed
this.hide();
    }//GEN-LAST:event_SaveAPScores_ButtonActionPerformed

    private void ResetAPScores_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetAPScores_ButtonActionPerformed
this.setVisible(false); //this will close frame i.e. NewJFrame

new TOEFL_Yes().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_ResetAPScores_ButtonActionPerformed

    private void ReadingScore_ComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReadingScore_ComboBoxMouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_ReadingScore_ComboBoxMouseClicked

    private void SaveAPScores_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveAPScores_ButtonMouseClicked

    }//GEN-LAST:event_SaveAPScores_ButtonMouseClicked

    private void ReadingScore_ComboBoxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ReadingScore_ComboBoxAncestorAdded

    }//GEN-LAST:event_ReadingScore_ComboBoxAncestorAdded

    private void ReadingScore_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ReadingScore_ComboBoxItemStateChanged

    }//GEN-LAST:event_ReadingScore_ComboBoxItemStateChanged

    private void APCoursesNumber_ComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox2ItemStateChanged

    private void APCoursesNumber_ComboBox2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox2AncestorAdded

    private void APCoursesNumber_ComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox2MouseClicked

    private void APCoursesNumber_ComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox2ActionPerformed

    private void APCoursesNumber_ComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox3ItemStateChanged

    private void APCoursesNumber_ComboBox3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox3AncestorAdded

    private void APCoursesNumber_ComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox3MouseClicked

    private void APCoursesNumber_ComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox3ActionPerformed

    private void ListeningScore_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListeningScore_ComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeningScore_ComboBoxItemStateChanged

    private void ListeningScore_ComboBoxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ListeningScore_ComboBoxAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeningScore_ComboBoxAncestorAdded

    private void ListeningScore_ComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListeningScore_ComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeningScore_ComboBoxMouseClicked

    private void ListeningScore_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeningScore_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeningScore_ComboBoxActionPerformed

    private void APCoursesNumber_ComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox4ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox4ItemStateChanged

    private void APCoursesNumber_ComboBox4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox4AncestorAdded

    private void APCoursesNumber_ComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox4MouseClicked

    private void APCoursesNumber_ComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox4ActionPerformed

    private void SpeakingScore_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SpeakingScore_ComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeakingScore_ComboBoxItemStateChanged

    private void SpeakingScore_ComboBoxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SpeakingScore_ComboBoxAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeakingScore_ComboBoxAncestorAdded

    private void SpeakingScore_ComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpeakingScore_ComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeakingScore_ComboBoxMouseClicked

    private void SpeakingScore_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeakingScore_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeakingScore_ComboBoxActionPerformed

    private void APCoursesNumber_ComboBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox6ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox6ItemStateChanged

    private void APCoursesNumber_ComboBox6AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox6AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox6AncestorAdded

    private void APCoursesNumber_ComboBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox6MouseClicked

    private void APCoursesNumber_ComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APCoursesNumber_ComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APCoursesNumber_ComboBox6ActionPerformed

    private void WritingScore_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_WritingScore_ComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_WritingScore_ComboBoxItemStateChanged

    private void WritingScore_ComboBoxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_WritingScore_ComboBoxAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_WritingScore_ComboBoxAncestorAdded

    private void WritingScore_ComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WritingScore_ComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_WritingScore_ComboBoxMouseClicked

    private void WritingScore_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WritingScore_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WritingScore_ComboBoxActionPerformed

    private void SaveAPScores_Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveAPScores_Button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveAPScores_Button1MouseClicked

    private void SaveAPScores_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAPScores_Button1ActionPerformed
int TOEFLScore = ReadingScore_ComboBox.getSelectedIndex() + ListeningScore_ComboBox.getSelectedIndex()+SpeakingScore_ComboBox.getSelectedIndex()+WritingScore_ComboBox.getSelectedIndex();   
TOEFLScore_TextField.setText("" + TOEFLScore);// TODO add your handling code here:
    }//GEN-LAST:event_SaveAPScores_Button1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TOEFL_Yes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TOEFL_Yes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TOEFL_Yes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TOEFL_Yes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TOEFL_Yes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> APCoursesNumber_ComboBox2;
    private javax.swing.JComboBox<String> APCoursesNumber_ComboBox3;
    private javax.swing.JComboBox<String> APCoursesNumber_ComboBox4;
    private javax.swing.JComboBox<String> APCoursesNumber_ComboBox6;
    private javax.swing.JLabel AcademicsPage_Label;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel GoBack_Label;
    private javax.swing.JLabel Heading_Label;
    private javax.swing.JLabel Heading_Label1;
    private javax.swing.JComboBox<String> ListeningScore_ComboBox;
    private javax.swing.JComboBox<String> ReadingScore_ComboBox;
    private javax.swing.JToggleButton ResetAPScores_Button;
    private javax.swing.JToggleButton SaveAPScores_Button;
    private javax.swing.JToggleButton SaveAPScores_Button1;
    private javax.swing.JComboBox<String> SpeakingScore_ComboBox;
    public static javax.swing.JTextField TOEFLScore_TextField;
    private javax.swing.JComboBox<String> WritingScore_ComboBox;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}