/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultRowSorter;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import static main.GPA_Yes.UnweightedGPA_ComboBox;
import static main.GPA_Yes.WeightedGPA_ComboBox;
import static main.SAT_Yes.FirstEnglishMark_ComboBox;
import static main.SAT_Yes.SecondEnglishMark_ComboBox;
import static main.SAT_Yes.ThirdEnglishMark_ComboBox;
import static main.SAT_Yes.FirstMathematicsMark_ComboBox;
import static main.SAT_Yes.SecondMathematicsMark_ComboBox;
import static main.SAT_Yes.ThirdMathematicsMark_ComboBox;
import static main.Field.FirstChoice_ComboBox;
import static main.Field.SecondChoice_ComboBox;
import javax.swing.table.*;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.ListSelectionEvent;
import static main.Academics.StudentID;
import static main.GPA_Yes.UnweightedGPA_ComboBox;
import static main.GPA_Yes.WeightedGPA_ComboBox;
import static main.IB_Yes.TotalIBScore_TextField;
import static main.SAT_Yes.SATSuperscore_TextField;
import static main.TOEFL_Yes.TOEFLScore_TextField;
import static main.Budget.Budget_ComboBox;

/**
 *
 * @author Sandeep
 */
public class UniversityList extends javax.swing.JFrame {
DefaultTableModel model;
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;

    /**
     * Creates new form Home_Data
     */
    public UniversityList() {
initComponents();
//Show_Users_In_JTable();        
    }
    public Connection getConnection()
   {
       Connection con;
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/StudentBase", "root","");
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Finished_Button = new javax.swing.JToggleButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        UniversityTable = new javax.swing.JTable();
        Display_Button = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));

        Exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Student_Male_48px.png"))); // NOI18N
        jLabel15.setText("University List");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_Long_Arrow_Left_48px_2.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel15))
                .addContainerGap(887, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Raleway SemiBold", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("The following list includes the particular \nuniversities related to your field of study. With \nthat in mind, the universities that have been \nshown are mindful of your budget. Also  in this\ncolumn would be the Percentage of Acceptance \nto the particular universities\n.");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        Finished_Button.setFont(new java.awt.Font("Raleway SemiBold", 3, 12)); // NOI18N
        Finished_Button.setText("FINISHED");
        Finished_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Finished_ButtonMouseClicked(evt);
            }
        });
        Finished_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Finished_ButtonActionPerformed(evt);
            }
        });

        UniversityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UniversityName", "GPA", "UniversitySATScore", "Fees", "UniversityGPA", "PercentageAcceptance", "Field"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UniversityTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                UniversityTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane6.setViewportView(UniversityTable);

        Display_Button.setFont(new java.awt.Font("Raleway SemiBold", 3, 12)); // NOI18N
        Display_Button.setText("Display");
        Display_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Display_ButtonMouseClicked(evt);
            }
        });
        Display_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Display_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Display_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Finished_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(Display_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Finished_Button))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        System.exit(0);    // TODO add your handling code here:
    }//GEN-LAST:event_ExitMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        new Home().show();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MousePressed

    private void Finished_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Finished_ButtonMouseClicked

    }//GEN-LAST:event_Finished_ButtonMouseClicked

    private void Finished_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Finished_ButtonActionPerformed
        this.hide();
        Home frm = new Home();
        frm.setVisible(true);
    }//GEN-LAST:event_Finished_ButtonActionPerformed
/**/
    private void Display_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Display_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Display_ButtonMouseClicked

    private void Display_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Display_ButtonActionPerformed
     ArrayList<Useer> usersList = new ArrayList<Useer>();
       Connection connection = getConnection();
      
       PreparedStatement ps;
       ResultSet rs;
       double lower = Double.parseDouble(Budget_ComboBox.getSelectedItem().toString().substring(1, 7));
       double upper = Double.parseDouble(Budget_ComboBox.getSelectedItem().toString().substring(10));
       String field1 = (String) FirstChoice_ComboBox.getSelectedItem();
       String field2 = (String) SecondChoice_ComboBox.getSelectedItem();
       
       try {
           ps = connection.prepareStatement("SELECT * FROM universityinfo WHERE (Fees <= ?) AND (Field = ?)");
           ps.setDouble(1,upper);
           ps.setString(2, field1);
           rs = ps.executeQuery();
           Useer user;
           while(rs.next())
           {
               user = new Useer(rs.getString("UniversityName"),rs.getString("GPA"),rs.getString("UniversitySATScore"),rs.getDouble("Fees"), rs.getString("Field"));
               usersList.add(user);
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
       try {
           ps = connection.prepareStatement("SELECT * FROM universityinfo WHERE (Fees <= ?) AND (Field = ?)");
           ps.setDouble(1,upper);
           ps.setString(2, field2);
           rs = ps.executeQuery();
           Useer user;
           while(rs.next())
           {
               user = new Useer(rs.getString("UniversityName"),rs.getString("GPA"),rs.getString("UniversitySATScore"),rs.getDouble("Fees"), rs.getString("Field"));
               usersList.add(user);
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
       
       Object[] row = new Object[7];
       for(int i = 0; i < usersList.size(); i++)
       {
           double UniversityGPA = Double.parseDouble(usersList.get(i).getGPA())+Double.parseDouble(usersList.get(i).getUniversitySATScore());
           double PercentageAcceptance = ((Double.parseDouble((String) WeightedGPA_ComboBox.getSelectedItem())+Double.parseDouble(SATSuperscore_TextField.getText()))/UniversityGPA)*100;
           if (PercentageAcceptance >= 100)
           {
               PercentageAcceptance = 99;
           }
           row[0] = usersList.get(i).getUniversityName();
           row[1] = usersList.get(i).getGPA();
           row[2] = usersList.get(i).getUniversitySATScore();
           row[3] = usersList.get(i).getFees();
           row[4] = UniversityGPA;
           row[5] = PercentageAcceptance;
           row[6] = usersList.get(i).getField();
           
           DefaultTableModel model = (DefaultTableModel) UniversityTable.getModel();
           model.addRow(row);
       }   // TODO add your handling code here:
    }//GEN-LAST:event_Display_ButtonActionPerformed

    private void UniversityTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_UniversityTableAncestorAdded
TableColumn column = UniversityTable.getColumnModel().getColumn(4);
column.setMaxWidth(0);
column.setMinWidth(0);
    }//GEN-LAST:event_UniversityTableAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){

        java.awt.EventQueue.invokeLater(() -> {
            new UniversityList().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Display_Button;
    private javax.swing.JLabel Exit;
    private javax.swing.JToggleButton Finished_Button;
    private javax.swing.JTable UniversityTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}